### ISSUE TITLE
Veřejné heslo k gmailu

### ISSUE THREAD

**Issue by emololftw** [alnux/bfyp-at-nette-framework#1]
Ahoj, 

máš v gitu smtp cfg a tím přihlašovací údaje na gmail:

https://github.com/alnux/bfyp-at-nette-framework/blob/master/app/config/config.neon

**Comment by alnux** [comment]
Máte pravdu,
 je to přístup k demo účtu, který si vytvoříte v Gmailu, ale můžete jej změnit pomocí svých dat, jakmile jej nakonfigurujete. Mimochodem, neaktualizujte, funguje pouze s nette 2.3 a php 5.6 
Google Překladač.
